name       : xfce4-session
version    : 4.18.3
release    : 2
source     :
    - https://archive.xfce.org/src/xfce/xfce4-session/4.18/xfce4-session-4.18.3.tar.bz2 : 382f93e096ec6493098719cab8cc31b93ad9bb469c0715c0c5117d75fe7394ec
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Xfce's session manager.
description: |
    Xfce's session manager.
builddeps  :
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(sm)
    - iceauth
setup      : |
    %configure --disable-debug
build      : |
    %make
install    : |
    %make_install
